name: Java CI with JaCoCo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Verify
        # Lệnh verify để chạy test và tạo báo cáo JaCoCo
        run: mvn clean verify
        continue-on-error: true # Ép GitHub chạy tiếp kể cả khi có lỗi để lấy Artifact

      - name: Upload JaCoCo Report
        if: always() # Luôn luôn upload báo cáo dù thành công hay thất bại
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
